nodes = ["rancher2-ui", "knode01", "knode02", "knode03"]

rhelDockerVersion = "18.09.9-3.el7"

$script = <<-SCRIPT
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
echo net.bridge.bridge-nf-call-iptables=1 >> /etc/sysctl.conf
echo net.bridge.bridge-nf-call-ip6tables=1 >> /etc/sysctl.conf
sysctl -p
swapoff -a
sed -i '/swap/d' /etc/fstab
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

# Set SELinux in permissive mode (effectively disabling it)
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

yum install -y kubeadm kubectl --disableexcludes=kubernetes

if [ `hostname` == #{nodes[0]} ]; then
    wget https://github.com/rancher/rke/releases/download/v0.2.8/rke_linux-amd64
    chmod a+x rke_linux-amd64
    mv rke_linux-amd64 /usr/local/bin/rke
fi
SCRIPT

$gensshkey = <<-SCRIPT
ssh-keygen -q -t rsa -N ""
SCRIPT

hostname = ""

Vagrant.configure("2") do |config|
    nodes.each_with_index  do |srvname, index|
        config.vm.define "#{srvname}" do |m|
            m.vm.provider "virtualbox" do |vb|
                vb.name = "#{srvname}"
                vb.memory = "2048"
                vb.cpus = "2"
            end
            m.vm.box = "bento/centos-7.3"
            m.vm.hostname = "#{srvname}"
            m.vm.network "private_network", ip: "192.168.70.12#{index}"
        end
        config.vm.provision "generate ssh key", type: "shell", 
                        privileged: false,
                        inline: "hostname > /vagrant/hostname.txt"
        config.vm.provision "generate ssh key", type: "shell", 
                        privileged: false,
                        inline: $gensshkey
        config.vm.provision "update-system", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "yum update -y"
        config.vm.provision "yum-utils", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "yum install -y yum-utils device-mapper-persistent-data lvm2"
        config.vm.provision "add docker repo", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
        config.vm.provision "install docker", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "yum install -y docker-ce-#{rhelDockerVersion} docker-ce-cli-#{rhelDockerVersion} containerd.io"
        config.vm.provision "enable docker", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "systemctl enable --now docker"
        config.vm.provision "allow user", type: "shell",
            preserve_order: true,
            run: "always",
            inline: "usermod -aG docker vagrant"
        config.vm.provision "optimization", type: "shell", inline: $script
        
    end
    #nodes.each_with_index  do |srvname, index|
    #    config.vm.define "#{srvname}" do |m|
    #        m.trigger.after :up do |t|
    #            t.name = "generate ssh key"
    #            t.run = {privileged: false, inline: $gensshkey}
    #        end
    #    end
    #end
end



